### ISSUE TITLE
1138. Alphabet Board Path

### ISSUE THREAD

**Issue by kingsamadesu** [RakhmedovRS/LeetCode#60]
[1138. Alphabet Board Path](url)

**Comment by kingsamadesu** [comment]
can i add this one

**Comment by RakhmedovRS** [comment]
Hello @kingsamadesu . Do you want me to solve this problem?

**Comment by kingsamadesu** [comment]
For sure @RakhmedovRS

**Comment by RakhmedovRS** [comment]
@kingsamadesu I've solved it for you. Watch for updates, I'll add some comments and add will push it to this repo.

**Comment by RakhmedovRS** [comment]
@kingsamadesu here's a solution https://github.com/RakhmedovRS/LeetCode/blob/master/src/main/java/AlphabetBoardPath.java
